# Generated by Django 4.2.6 on 2023-11-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cassisapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='season',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
