# Generated by Django 4.2.6 on 2023-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cassisapi', '0002_alter_article_season_delete_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
