# Generated by Django 4.2.6 on 2023-11-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cassisapi', '0004_outfit_outfitarticle_outfit_articles_outfit_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
